# tox.ini
[tox]
envlist = lint, test, coverage

[testenv]
deps =
    pytest
    pytest-cov
    -rrequirements.txt
commands =
    pytest --cov=app --cov-report=term-missing

[testenv:lint]
deps = flake8
commands = flake8 app --max-line-length=119

[testenv:coverage]
deps =
    pytest
    pytest-cov
    -rrequirements.txt
allowlist_externals = which
commands =
    pytest --cov=app --cov-report=html
